# Filters used by [dorny/path-filters](https://github.com/dorny/paths-filter)
# to detect changes in each subproject, and only run the corresponding jobs.

# Dependencies and common workspace configuration.
rust-config: &rust-config
  - "Cargo.lock"
  - "Cargo.toml"
  - ".github/workflows/ci-rs.yml"

model: &model
  - *rust-config
  - "hugr-model/**"

llvm: &llvm
  - *rust-config
  - "hugr-llvm/**"
  - "hugr-core/**"

rust: &rust
  - *rust-config
  - *model
  - *llvm
  - "hugr/**"
  - "hugr-cli/**"
  - "hugr-core/**"
  - "hugr-passes/**"
  - "specification/schema/**"

std-extensions:
  - "specification/std_extensions/**"

python:
  - *rust
  - "hugr-py/**"
  - "pyproject.toml"
  - "uv.lock"
  - "specification/schema/**"
  - ".github/workflows/ci-py.yml"
