#!/bin/sh

# A pre-push hook for rust codebases that checks formatting, clippy, and tests

set -eu

if [[ "${IGNORE_RUSTHOOKS:=0}" -ne 0 ]]; then
    echo "Ignoring rusthooks"
    exit 0
fi

if ! cargo fmt -- --check
then
    echo "There are some code style issues."
    echo "Run cargo fmt first."
    exit 1
fi

if ! cargo clippy --all-targets --all-features --workspace -- -D warnings
then
    echo "There are some clippy issues."
    exit 1
fi

if ! cargo test --all-features
then
    echo "There are some test issues."
    exit 1
fi

# Run `ruff` python formatting
if ! poetry run ruff format --check
then
    echo ""
    echo "There are some python code style issues."
    echo "Run `poetry run ruff format` first."
    exit 1
fi

# Run `mypy` for python type checking
if ! poetry run mypy .
then
    echo ""
    echo "There are some python code style issues."
    echo "Fix the warnings returned by `poetry run mypy .` first."
    exit 1
fi

# Run `ruff` python linting
if ! poetry run ruff check
then
    echo ""
    echo "There are some python linting issues."
    exit 1
fi

exit 0
