[default.extend-identifiers]
bck = "bck" # BiMap uses abbreviation
ser_it = "ser_it"
SerCollection = "SerCollection"
strat = "strat" # common abbreviation for strategy
# some arithmetic op names:
inot = "inot"
fle = "fle"
ine = "ine"
