name: Add issues to project board
on:
  issues:
    types:
      - opened

jobs:
    add-to-project:
        uses: CQCL/hugrverse-actions/.github/workflows/add-to-project.yml@main
        with:
            project-url: https://github.com/orgs/CQCL-DEV/projects/10
        secrets:
            GITHUB_PAT: ${{ secrets.ADD_TO_PROJECT_PAT }}