# A workflow that returns valid status checks for required checks that are
# skipped in the main workflow (due to the push request not modifying the code).
#
# This is an annoying workaround as GitHub does not support workflow path
# filtering + required checks.
# See https://github.com/orgs/community/discussions/44490

name: Continuous integration 🐍 - skipped

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'quantinuum-hugr-py/**'
      - 'pyproject.toml'
      - '!**/*.md'
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    name: check python (3.10)
    steps:
      - name: Do nothing
        run: echo "This is a dummy step to return a valid status check"
