# A workflow that returns valid status checks for required checks that are
# skipped in the main workflow (due to the push request not modifying the code).
#
# This is an annoying workaround as GitHub does not support workflow path
# filtering + required checks.
# See https://github.com/orgs/community/discussions/44490

name: Continuous integration 🦀 - skipped

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'quantinuum-hugr/**'
      - 'specification/schema/**'
      - 'Cargo.toml'
      - '!**/*.md'
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    name: check
    steps:
      - name: Do nothing
        run: echo "This is a dummy step to return a valid status check"

  tests:
    runs-on: ubuntu-latest
    name: tests (Rust stable)
    steps:
      - name: Do nothing
        run: echo "This is a dummy step to return a valid status check"
