# Automatic changelog, version bumping, and semver-checks with release-plz for rust projects
name: Release-plz 🦀

on:
  push:
    branches:
      - main


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.github.event_name }}
  cancel-in-progress: true

env:
  LLVM_VERSION: "14.0"

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    environment: crate-release
    permissions:
      id-token: write     # Required for OIDC token exchange
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.HUGRBOT_PAT }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # These are needed when doing a crate release, since `cargo release`
      # checks that the crate can be compiled before publishing it.
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: ${{ env.LLVM_VERSION }}
          # Use a temporary directory to avoid polluting the workspace,
          # otherwise release-plz fails due to uncommitted changes.
          directory: ${{ runner.temp }}/llvm

      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.HUGRBOT_PAT }}
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
